parameters:
    automatic_update.options:
        secret: secret
        dry_run_commands:
#            - "svn status -u"
            - "php composer.phar update --dry-run --ansi"
            - "app/console doctrine:schema:update --dump-sql"
        execute_commands:
#            - "svn up"
            - "php composer.phar update --ansi"
            - "app/console doctrine:schema:update --force"
