parameters:
    automatic_update.class: Lsw\AutomaticUpdateBundle\Software\AutomaticUpdate
    automatic_update.data_collector.class: Lsw\AutomaticUpdateBundle\DataCollector\AutomaticUpdateDataCollector
    automatic_update.data_collector.template: "LswAutomaticUpdateBundle:Collector:update"
    lsw_ansi_extension.class: Lsw\AutomaticUpdateBundle\Extension\AnsiExtension

services:
    automatic_update:
        class: %automatic_update.class%
        arguments: [%automatic_update.options%]
    automatic_update.data_collector:
        class: %automatic_update.data_collector.class%
        arguments: [@kernel]
        tags:
            - { name: data_collector, template: %automatic_update.data_collector.template%, id:"update"}
    lsw_ansi_extension:
        class: %lsw_ansi_extension.class%
        tags:
            - { name: twig.extension }